// Code generated by tool/codegen from spec/keys.yaml. DO NOT EDIT.
// 所有 Redis key 规范参见: 

package keys

import "fmt"

// ============================================================================
// §2.1 保留路径前缀
// ============================================================================
const (
	PrefixFuncBuiltin = "/func/builtin/" // 内置算子根
	PrefixFuncExop = "/func/exop-" // extended-op 后端根
	PrefixMetathread = "/metathread/" // 元线程运行时根
	PrefixSysBackend = "/sys/backend/" // 后端能力注册根
	PrefixSysCounter = "/sys/counter/" // 计数器根
	PrefixSysDaemon = "/sys/daemon/" // 守护进程根
	PrefixSysHeartbeat = "/sys/heartbeat/" // 心跳根
	PrefixSysIpcCmd = "/sys/ipc/cmd/" // 命令队列根
	PrefixSysIpcNotify = "/sys/ipc/notify/" // 通知队列根
	PrefixUsrFunc = "/usr/func/" // 用户函数源码根
)

// ============================================================================
// Key 构造函数
// ============================================================================

// BuiltinOp VM 内置算子 (标量运算、控制流)
//   category: 分类: int/float/double/string/bool/ctrl
//   op: 算子名
func BuiltinOp(category string, op string) string {
	return fmt.Sprintf("/func/builtin/%s/%s", category, op)
}

// ExopFunc extended-op 后端算子 (op-plat 执行)
//   backend: 后端: cuda/metal/cpu
//   category: 分类: tensor/math/nn
//   op: 算子名
func ExopFunc(backend string, category string, op string) string {
	return fmt.Sprintf("/func/exop-%s/%s/%s", backend, category, op)
}

// UsrFunc 用户函数签名
//   name: 
func UsrFunc(name string) string {
	return fmt.Sprintf("/usr/func/%s", name)
}

// UsrFuncInst 用户函数指令
//   name: 
//   n: 
func UsrFuncInst(name string, n int) string {
	return fmt.Sprintf("/usr/func/%s/%d", name, n)
}

// UsrFuncBranch 用户函数控制流分支
//   name: 
//   n: 
//   branch: then / else / body
//   m: 
func UsrFuncBranch(name string, n int, branch string, m int) string {
	return fmt.Sprintf("/usr/func/%s/%d/%s/%d", name, n, branch, m)
}

// DaemonOp op-plat 进程注册
//   instance: 
func DaemonOp(instance string) string {
	return fmt.Sprintf("/sys/daemon/op/%s", instance)
}

// DaemonHeap heap-plat 进程注册
//   instance: 
func DaemonHeap(instance string) string {
	return fmt.Sprintf("/sys/daemon/heap/%s", instance)
}

// DaemonVM VM 实例注册
//   id: 
func DaemonVM(id string) string {
	return fmt.Sprintf("/sys/daemon/vm/%s", id)
}

// BackendList 后端算子列表
//   program: 
func BackendList(program string) string {
	return fmt.Sprintf("/sys/backend/%s/list", program)
}

// BackendOpMeta 算子元数据 (dtype, max_shape, symbols, fusion_group)
//   program: 
//   opname: 
func BackendOpMeta(program string, opname string) string {
	return fmt.Sprintf("/sys/backend/%s/ops/%s", program, opname)
}

// CmdOp op-plat 命令队列
//   instance: 
func CmdOp(instance string) string {
	return fmt.Sprintf("/sys/ipc/cmd/op/%s", instance)
}

// CmdHeap heap-plat 命令队列
//   program: 
//   device: 
func CmdHeap(program string, device string) string {
	return fmt.Sprintf("/sys/ipc/cmd/heap/%s/%s", program, device)
}

// NotifyVM VM 唤醒通知 (pysdk → VM)
func NotifyVM() string {
	return "/sys/ipc/notify/vm"
}

// NotifyDone 操作完成通知 (op-plat / heap-plat → VM)
//   vtid: 
func NotifyDone(vtid string) string {
	return fmt.Sprintf("/sys/ipc/notify/done/%s", vtid)
}

// SysConfig 全局配置
func SysConfig() string {
	return "/sys/config"
}

// VtidCounter vthread ID 自增计数器
func VtidCounter() string {
	return "/sys/counter/vtid"
}

// SysHeartbeat 组件心跳
//   id: 
func SysHeartbeat(id string) string {
	return fmt.Sprintf("/sys/heartbeat/%s", id)
}

// Metathread 元线程自身状态 — value: {pc, status}
//   vtid: 
func Metathread(vtid string) string {
	return fmt.Sprintf("/metathread/%s", vtid)
}

// MetathreadPrefix 元线程子树前缀 (SCAN)
//   vtid: 
func MetathreadPrefix(vtid string) string {
	return fmt.Sprintf("/metathread/%s/", vtid)
}

// MetathreadInstOp 指令操作码 — 二维坐标 [addr0, 0]
//   vtid: 
//   addr0: 
func MetathreadInstOp(vtid string, addr0 string) string {
	return fmt.Sprintf("/metathread/%s/[%s,0]", vtid, addr0)
}

// MetathreadInstRead 指令读参数 — 二维坐标 [addr0, -n]
//   vtid: 
//   addr0: 
//   n: 
func MetathreadInstRead(vtid string, addr0 string, n int) string {
	return fmt.Sprintf("/metathread/%s/[%s,-%d]", vtid, addr0, n)
}

// MetathreadInstWrite 指令写参数 — 二维坐标 [addr0, n]
//   vtid: 
//   addr0: 
//   n: 
func MetathreadInstWrite(vtid string, addr0 string, n int) string {
	return fmt.Sprintf("/metathread/%s/[%s,%d]", vtid, addr0, n)
}

// MetathreadSlot 命名槽位 — 与指令坐标平级
//   vtid: 
//   name: 
func MetathreadSlot(vtid string, name string) string {
	return fmt.Sprintf("/metathread/%s/%s", vtid, name)
}

// MetathreadSubstack 子栈根 — CALL 产生的子维度
//   vtid: 
//   addr0: 
func MetathreadSubstack(vtid string, addr0 string) string {
	return fmt.Sprintf("/metathread/%s/[%s,0]/", vtid, addr0)
}

// MetathreadWildcard 所有元线程通配
func MetathreadWildcard() string {
	return "/metathread/*"
}

// BackendListWildcard 所有后端算子列表通配
func BackendListWildcard() string {
	return "/sys/backend/*/list"
}

// DaemonWildcard 所有守护进程通配
func DaemonWildcard() string {
	return "/sys/daemon/*/*"
}


// ============================================================================
//  状态
// ============================================================================

type MetathreadStatus string
const (
	MetathreadStatusInit MetathreadStatus = "init" // 已创建，待 VM 拾取
	MetathreadStatusRunning MetathreadStatus = "running" // VM 正在调度执行
	MetathreadStatusWait MetathreadStatus = "wait" // 等待异步操作
	MetathreadStatusError MetathreadStatus = "error" // 执行出错
	MetathreadStatusDone MetathreadStatus = "done" // 执行完毕，栈待 GC
)

func (s MetathreadStatus) IsTerminal() bool {
	return s == MetathreadStatusError || s == MetathreadStatusDone
}


// ============================================================================
// 常量
// ============================================================================

const OpStatusOK = "ok" // op-plat 完成 — 成功

const OpStatusError = "error" // op-plat 完成 — 失败

const EventNewVthread = "new_vthread" // 通知事件: 新元线程

var Backends = []string{  } // 支持的后端

const DeviceGPU0 = "gpu0" // 默认 GPU 设备

const DeviceCPU = "cpu" // CPU 设备

const NodeDefault = "n1" // 默认节点

const ShmPrefix = "/deepx_t_" // tensor shm 前缀

const EntryFunc = "main" // 默认入口函数名


// ============================================================================
// 工具函数
// ============================================================================

func IsRelative(param string) bool {
	return len(param) >= 2 && param[:2] == "./"
}

func ResolveRelative(vtid, param string) string {
	if IsRelative(param) {
		return Metathread(vtid) + "/" + param[2:]
	}
	return param
}

func FuncMain() string { return UsrFunc("main") }
