// Code generated by tool/codegen from spec/keys.yaml. DO NOT EDIT.
// 所有 Redis key 规范参见: 

#pragma once

#include <string>
#include <string_view>

namespace deepx::keys {

// ============================================================================
// §2.1 保留路径前缀
// ============================================================================

inline constexpr std::string_view kPrefixFuncBuiltin = "/func/builtin/"; // 内置算子根
inline constexpr std::string_view kPrefixFuncExop = "/func/exop-"; // extended-op 后端根
inline constexpr std::string_view kPrefixMetathread = "/metathread/"; // 元线程运行时根
inline constexpr std::string_view kPrefixSysBackend = "/sys/backend/"; // 后端能力注册根
inline constexpr std::string_view kPrefixSysCounter = "/sys/counter/"; // 计数器根
inline constexpr std::string_view kPrefixSysDaemon = "/sys/daemon/"; // 守护进程根
inline constexpr std::string_view kPrefixSysHeartbeat = "/sys/heartbeat/"; // 心跳根
inline constexpr std::string_view kPrefixSysIpcCmd = "/sys/ipc/cmd/"; // 命令队列根
inline constexpr std::string_view kPrefixSysIpcNotify = "/sys/ipc/notify/"; // 通知队列根
inline constexpr std::string_view kPrefixUsrFunc = "/usr/func/"; // 用户函数源码根

// ============================================================================
// Key 构造函数
// ============================================================================

// BuiltinOp: VM 内置算子 (标量运算、控制流)
inline std::string BuiltinOp(const std::string& category, const std::string& op) {
    return "/func/builtin/" + category + "/" + op;
}

// ExopFunc: extended-op 后端算子 (op-plat 执行)
inline std::string ExopFunc(const std::string& backend, const std::string& category, const std::string& op) {
    return "/func/exop-" + backend + "/" + category + "/" + op;
}

// UsrFunc: 用户函数签名
inline std::string UsrFunc(const std::string& name) {
    return "/usr/func/" + name;
}

// UsrFuncInst: 用户函数指令
inline std::string UsrFuncInst(const std::string& name, int n) {
    return "/usr/func/" + name + "/" + std::to_string(n);
}

// UsrFuncBranch: 用户函数控制流分支
inline std::string UsrFuncBranch(const std::string& name, int n, const std::string& branch, int m) {
    return "/usr/func/" + name + "/" + std::to_string(n) + "/" + branch + "/" + std::to_string(m);
}

// DaemonOp: op-plat 进程注册
inline std::string DaemonOp(const std::string& instance) {
    return "/sys/daemon/op/" + instance;
}

// DaemonHeap: heap-plat 进程注册
inline std::string DaemonHeap(const std::string& instance) {
    return "/sys/daemon/heap/" + instance;
}

// DaemonVM: VM 实例注册
inline std::string DaemonVM(const std::string& id) {
    return "/sys/daemon/vm/" + id;
}

// BackendList: 后端算子列表
inline std::string BackendList(const std::string& program) {
    return "/sys/backend/" + program + "/list";
}

// BackendOpMeta: 算子元数据 (dtype, max_shape, symbols, fusion_group)
inline std::string BackendOpMeta(const std::string& program, const std::string& opname) {
    return "/sys/backend/" + program + "/ops/" + opname;
}

// CmdOp: op-plat 命令队列
inline std::string CmdOp(const std::string& instance) {
    return "/sys/ipc/cmd/op/" + instance;
}

// CmdHeap: heap-plat 命令队列
inline std::string CmdHeap(const std::string& program, const std::string& device) {
    return "/sys/ipc/cmd/heap/" + program + "/" + device;
}

// NotifyVM: VM 唤醒通知 (pysdk → VM)
inline constexpr std::string_view NotifyVM = "/sys/ipc/notify/vm";

// NotifyDone: 操作完成通知 (op-plat / heap-plat → VM)
inline std::string NotifyDone(const std::string& vtid) {
    return "/sys/ipc/notify/done/" + vtid;
}

// SysConfig: 全局配置
inline constexpr std::string_view SysConfig = "/sys/config";

// VtidCounter: vthread ID 自增计数器
inline constexpr std::string_view VtidCounter = "/sys/counter/vtid";

// SysHeartbeat: 组件心跳
inline std::string SysHeartbeat(const std::string& id) {
    return "/sys/heartbeat/" + id;
}

// Metathread: 元线程自身状态 — value: {pc, status}
inline std::string Metathread(const std::string& vtid) {
    return "/metathread/" + vtid;
}

// MetathreadPrefix: 元线程子树前缀 (SCAN)
inline std::string MetathreadPrefix(const std::string& vtid) {
    return "/metathread/" + vtid + "/";
}

// MetathreadInstOp: 指令操作码 — 二维坐标 [addr0, 0]
inline std::string MetathreadInstOp(const std::string& vtid, const std::string& addr0) {
    return "/metathread/" + vtid + "/[" + addr0 + ",0]";
}

// MetathreadInstRead: 指令读参数 — 二维坐标 [addr0, -n]
inline std::string MetathreadInstRead(const std::string& vtid, const std::string& addr0, int n) {
    return "/metathread/" + vtid + "/[" + addr0 + ",-" + std::to_string(n) + "]";
}

// MetathreadInstWrite: 指令写参数 — 二维坐标 [addr0, n]
inline std::string MetathreadInstWrite(const std::string& vtid, const std::string& addr0, int n) {
    return "/metathread/" + vtid + "/[" + addr0 + "," + std::to_string(n) + "]";
}

// MetathreadSlot: 命名槽位 — 与指令坐标平级
inline std::string MetathreadSlot(const std::string& vtid, const std::string& name) {
    return "/metathread/" + vtid + "/" + name;
}

// MetathreadSubstack: 子栈根 — CALL 产生的子维度
inline std::string MetathreadSubstack(const std::string& vtid, const std::string& addr0) {
    return "/metathread/" + vtid + "/[" + addr0 + ",0]/";
}

// MetathreadWildcard: 所有元线程通配
inline constexpr std::string_view MetathreadWildcard = "/metathread/*";

// BackendListWildcard: 所有后端算子列表通配
inline constexpr std::string_view BackendListWildcard = "/sys/backend/*/list";

// DaemonWildcard: 所有守护进程通配
inline constexpr std::string_view DaemonWildcard = "/sys/daemon/*/*";


// ============================================================================
//  状态
// ============================================================================

namespace metathread_status {
    inline constexpr std::string_view kInit = "init"; // 已创建，待 VM 拾取
    inline constexpr std::string_view kRunning = "running"; // VM 正在调度执行
    inline constexpr std::string_view kWait = "wait"; // 等待异步操作
    inline constexpr std::string_view kError = "error"; // 执行出错
    inline constexpr std::string_view kDone = "done"; // 执行完毕，栈待 GC
} // namespace metathread_status


// ============================================================================
// 常量
// ============================================================================

inline constexpr std::string_view kOpStatusOK = "ok"; // op-plat 完成 — 成功

inline constexpr std::string_view kOpStatusError = "error"; // op-plat 完成 — 失败

inline constexpr std::string_view kEventNewVthread = "new_vthread"; // 通知事件: 新元线程

// 支持的后端
// (C++ 中列表定义为 constexpr array)

inline constexpr std::string_view kDeviceGPU0 = "gpu0"; // 默认 GPU 设备

inline constexpr std::string_view kDeviceCPU = "cpu"; // CPU 设备

inline constexpr std::string_view kNodeDefault = "n1"; // 默认节点

inline constexpr std::string_view kShmPrefix = "/deepx_t_"; // tensor shm 前缀

inline constexpr std::string_view kEntryFunc = "main"; // 默认入口函数名


} // namespace deepx::keys
