// Code generated by tool/codegen from spec/keys.yaml. DO NOT EDIT.
// 所有 Redis key 规范参见: 

// ============================================================================
// Redis Key — 服务端 key 路径
// ============================================================================

export const KEY = {
  /** VM 内置算子 (标量运算、控制流) */
  BuiltinOp(category: string, op: string): string { return `/func/builtin/${category}/${op}` },
  /** extended-op 后端算子 (op-plat 执行) */
  ExopFunc(backend: string, category: string, op: string): string { return `/func/exop-${backend}/${category}/${op}` },
  /** 用户函数签名 */
  UsrFunc(name: string): string { return `/usr/func/${name}` },
  /** 用户函数指令 */
  UsrFuncInst(name: string, n: number): string { return `/usr/func/${name}/${n}` },
  /** 用户函数控制流分支 */
  UsrFuncBranch(name: string, n: number, branch: string, m: number): string { return `/usr/func/${name}/${n}/${branch}/${m}` },
  /** op-plat 进程注册 */
  DaemonOp(instance: string): string { return `/sys/daemon/op/${instance}` },
  /** heap-plat 进程注册 */
  DaemonHeap(instance: string): string { return `/sys/daemon/heap/${instance}` },
  /** VM 实例注册 */
  DaemonVM(id: string): string { return `/sys/daemon/vm/${id}` },
  /** 后端算子列表 */
  BackendList(program: string): string { return `/sys/backend/${program}/list` },
  /** 算子元数据 (dtype, max_shape, symbols, fusion_group) */
  BackendOpMeta(program: string, opname: string): string { return `/sys/backend/${program}/ops/${opname}` },
  /** op-plat 命令队列 */
  CmdOp(instance: string): string { return `/sys/ipc/cmd/op/${instance}` },
  /** heap-plat 命令队列 */
  CmdHeap(program: string, device: string): string { return `/sys/ipc/cmd/heap/${program}/${device}` },
  /** VM 唤醒通知 (pysdk → VM) */
  NotifyVM(): string { return `/sys/ipc/notify/vm` },
  /** 操作完成通知 (op-plat / heap-plat → VM) */
  NotifyDone(vtid: string): string { return `/sys/ipc/notify/done/${vtid}` },
  /** 全局配置 */
  SysConfig(): string { return `/sys/config` },
  /** vthread ID 自增计数器 */
  VtidCounter(): string { return `/sys/counter/vtid` },
  /** 组件心跳 */
  SysHeartbeat(id: string): string { return `/sys/heartbeat/${id}` },
  /** 元线程自身状态 — value: {pc, status} */
  Metathread(vtid: string): string { return `/metathread/${vtid}` },
  /** 元线程子树前缀 (SCAN) */
  MetathreadPrefix(vtid: string): string { return `/metathread/${vtid}/` },
  /** 指令操作码 — 二维坐标 [addr0, 0] */
  MetathreadInstOp(vtid: string, addr0: string): string { return `/metathread/${vtid}/[${addr0},0]` },
  /** 指令读参数 — 二维坐标 [addr0, -n] */
  MetathreadInstRead(vtid: string, addr0: string, n: number): string { return `/metathread/${vtid}/[${addr0},-${n}]` },
  /** 指令写参数 — 二维坐标 [addr0, n] */
  MetathreadInstWrite(vtid: string, addr0: string, n: number): string { return `/metathread/${vtid}/[${addr0},${n}]` },
  /** 命名槽位 — 与指令坐标平级 */
  MetathreadSlot(vtid: string, name: string): string { return `/metathread/${vtid}/${name}` },
  /** 子栈根 — CALL 产生的子维度 */
  MetathreadSubstack(vtid: string, addr0: string): string { return `/metathread/${vtid}/[${addr0},0]/` },
  /** 所有元线程通配 */
  MetathreadWildcard(): string { return `/metathread/*` },
  /** 所有后端算子列表通配 */
  BackendListWildcard(): string { return `/sys/backend/*/list` },
  /** 所有守护进程通配 */
  DaemonWildcard(): string { return `/sys/daemon/*/*` },

} as const;

// ============================================================================
//  状态枚举
// ============================================================================

export enum MetathreadStatus {
  Init = "init", // 已创建，待 VM 拾取
  Running = "running", // VM 正在调度执行
  Wait = "wait", // 等待异步操作
  Error = "error", // 执行出错
  Done = "done", // 执行完毕，栈待 GC
}

export function isTerminalMetathreadStatus(s: string): boolean {
  return s === MetathreadStatus.Error || s === MetathreadStatus.Done;
}

export const MetathreadStatus_LABELS: Record<MetathreadStatus, string> = {
  [MetathreadStatus.Init]: '已创建，待 VM 拾取',
  [MetathreadStatus.Running]: 'VM 正在调度执行',
  [MetathreadStatus.Wait]: '等待异步操作',
  [MetathreadStatus.Error]: '执行出错',
  [MetathreadStatus.Done]: '执行完毕，栈待 GC',
};


// ============================================================================
// 常量
// ============================================================================

export const OpStatusOK = "ok"; // op-plat 完成 — 成功

export const OpStatusError = "error"; // op-plat 完成 — 失败

export const EventNewVthread = "new_vthread"; // 通知事件: 新元线程

export const Backends = [] as const;

export const DeviceGPU0 = "gpu0"; // 默认 GPU 设备

export const DeviceCPU = "cpu"; // CPU 设备

export const NodeDefault = "n1"; // 默认节点

export const ShmPrefix = "/deepx_t_"; // tensor shm 前缀

export const EntryFunc = "main"; // 默认入口函数名


// ============================================================================
// 默认值 (前后端共享语义)
// ============================================================================

export const DEFAULTS = {
  /** 默认入口函数名 */
  ENTRY_FUNC: 'main',
  /** 代码执行默认超时 (秒) */
  TIMEOUT_SEC: 60,
} as const;
